team:
  name: "Grupo 12 - DANN Project"
  members:
    - user: m.hernandezg234@uniandes.edu.co
      percentage: 25
    - user: ma.quinteror1@uniandes.edu.co
      percentage: 25
    - user: j.buriticar2@uniandes.edu.co
      percentage: 25
    - user: jd.marinb1@uniandes.edu.co
      percentage: 25
board: "https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/314/views/1"
docs: "https://misw-4301-desarrollo-apps-en-la-nube.github.io/202611-grupo12-proyecto/"


users_app:
  folder: users_app
  image_name: users-app
  image_tag: v1.0.0
  authors:
    - m.hernandezg234@uniandes.edu.co

posts_app:
  folder: posts_app
  image_name: posts-app
  image_tag: v1.0.0
  authors:
    - jd.marinb1@uniandes.edu.co

offers_app:
  folder: offers_app
  image_name: offers-app
  image_tag: v1.0.0
  authors:
    - j.buriticar2@uniandes.edu.co

routes_app:
  folder: routes_app
  image_name: routes-app
  image_tag: v1.0.0
  authors:
    - ma.quinteror1@uniandes.edu.co
