apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: offers-network
  labels:
    team: grupo12
spec:
  podSelector:
    matchLabels:
      app: offers-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: offers-app
      ports:
        - protocol: TCP
          port: 5432
