apiVersion: v1
kind: Service
metadata:
  name: offers-app-service
  labels:
    app: offers-app
    team: grupo12
spec:
  type: NodePort
  selector:
    app: offers-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP
