apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: posts-network
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: posts-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: posts-app
      ports:
        - protocol: TCP
          port: 5432