apiVersion: v1
kind: Service
metadata:
  name: routes-app-service
  namespace: default
spec:
  selector:
    app: routes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
