apiVersion: v1
kind: Service
metadata:
  name: users-db-service
  labels:
    app: users-db
spec:
  type: ClusterIP
  selector:
    app: users-db
  ports:
  - port: 5432 # Puerto esperado por el autocalificador
    targetPort: 5432
    protocol: TCP
